title: Jekyll Website Project Template
email: wynumarcu23@example.com
description: >- # this means to ignore newlines until "baseurl:"
 sdasdsd
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: marcuwynu23
github_username:  marcuwynu23

# Build settings
theme: minima
plugins:
  - jekyll-feed
port: 9000
