title: Jekyll Website Project Template
email: test@example.com
description: >- # this means to ignore newlines until "baseurl:"
 sdasdsd
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com



include:
  - _includes

  
layouts_dir: "_layouts"
default_layout: "default"
# Custom layout values
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
port: 9000
